name: ✨ Feature Request
description: Suggest an idea for this project
title: "✨ [Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the project documentation
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: Alternative approaches could be...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit users?
      placeholder: This would help users by...
    validations:
      required: true

  - type: checkboxes
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature is to implement?
      options:
        - label: Low complexity (simple change)
        - label: Medium complexity (moderate effort)
        - label: High complexity (significant effort)
        - label: I'm not sure

  - type: checkboxes
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - label: Critical (blocks my work)
        - label: High (would significantly improve my workflow)
        - label: Medium (would be nice to have)
        - label: Low (minor improvement)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: Additional information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would like to work on this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback during development